apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config # Name of the ConfigMap
  namespace: postgres
  labels:
    app: postgres
data:
  POSTGRES_DB: 'todos_db'
  POSTGRES_PASSWORD: 'postgres'
  POSTGRES_USER: 'postgres'
  PGDATA: '/var/lib/postgresql/data/pgdata'