apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  namespace: postgres
  labels:
    type: local
    app: postgres
spec:
  storageClassName: hostpath
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/mnt/datapostgres'