apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim
  namespace: postgres
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi