apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-appnode
  namespace: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appnode
  template:
    metadata:
      labels:
        app: appnode
    spec:
      containers:
        - name: todo-monolith
          image: jaimesalas/lc-todo-monolith:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: appnode-config