apiVersion: apps/v1
kind: Deployment
metadata:
  name: ejercicio-01-todo-app-deployment
  labels:
    app: ejercicio-01-todo-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: todo-app-imagen:latest
        imagePullPolicy: Never
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        ports:
        - containerPort: 80
        env:
          - name: NODE_ENV
            value: "development"
          - name: PORT
            value: "80"
